<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Partnership;
class PartnershipSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        Partnership::insert([
            ['name' => '가스신문', 'img_path' => $this->hashImageName('가스신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '가톨릭시보', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '간호사신문', 'img_path' => $this->hashImageName('간호사신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '건설경제신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '경기교육신보', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '경기산경신보', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '경남신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '경마문화신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '경우신보', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '골프신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '공안신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '공업신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '교통신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '국방전우신문', 'img_path' => $this->hashImageName('국방전우신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '국세신문', 'img_path' => $this->hashImageName('국세신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '국제기독교뉴스', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '국토매일', 'img_path' => $this->hashImageName('국토매일'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '국토자원경제', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '기독교신문', 'img_path' => $this->hashImageName('기독교신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '기독교연합신문', 'img_path' => $this->hashImageName('기독교연합신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '기독신문', 'img_path' => $this->hashImageName('기독신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '내외뉴스통신', 'img_path' => $this->hashImageName('내외뉴스통신'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '농경과 원예', 'img_path' => $this->hashImageName('농경과 원예'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '농기자재신문', 'img_path' => $this->hashImageName('농기자재신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '농수산신보', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '농수축산신문', 'img_path' => $this->hashImageName('농수축산신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '농수축산신보', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '농어촌경제신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '농업경제신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '농업인신문', 'img_path' => $this->hashImageName('농업인신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '농업축산신문', 'img_path' => $this->hashImageName('농업축산신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '농촌신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '농촌여성신문', 'img_path' => $this->hashImageName('농촌여성신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '농축유통신문', 'img_path' => $this->hashImageName('농축유통신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '농축환경신문', 'img_path' => $this->hashImageName('농축환경신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '대한건설정보', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '대한공론', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '대한교육신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '대한복지문화신문', 'img_path' => $this->hashImageName('대한복지문화신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '대한불교', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '대한전기신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '대한전기신보', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '더닥터', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '더바이어', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '데일리환경', 'img_path' => $this->hashImageName('데일리환경'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '독서신문', 'img_path' => $this->hashImageName('독서신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '동아산경신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '디텍티브뉴스', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '레저신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '마트저널', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '마포신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '말산업저널', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '메디칼업저버', 'img_path' => $this->hashImageName('메디칼업저버'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '물가신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '물류신문', 'img_path' => $this->hashImageName('물류신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '미술신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '밀교신문', 'img_path' => $this->hashImageName('밀교신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '반공신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '버섯정보신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '법률선진신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '법률신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '법정신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '병원신문', 'img_path' => $this->hashImageName('병원신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '보건신문', 'img_path' => $this->hashImageName('보건신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '보건신보', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '보험신보', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '본협회', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '볼링신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '불교신문', 'img_path' => $this->hashImageName('불교신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '뷰티누리', 'img_path' => $this->hashImageName('뷰티누리'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '새한신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '서초신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '선데이서울', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '세무사신문', 'img_path' => $this->hashImageName('세무사신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '소비자경제', 'img_path' => $this->hashImageName('소비자경제'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '수도건설신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '수산경제신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '수산신보', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '시사포커스', 'img_path' => $this->hashImageName('시사포커스'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '시정신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '시정일보', 'img_path' => $this->hashImageName('시정일보'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '시청각교육신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '식물저널', 'img_path' => $this->hashImageName('식물저널'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '식품외식경제', 'img_path' => $this->hashImageName('식품외식경제'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '식품음료신문', 'img_path' => $this->hashImageName('식품음료신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '식약신보', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CEO NEWS', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'CMN', 'img_path' => $this->hashImageName('CMN'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '아시아뉴스통신', 'img_path' => $this->hashImageName('아시아뉴스통신'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '아파트관리신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '애플경제', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '약국신문', 'img_path' => $this->hashImageName('약국신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '약사공론', 'img_path' => $this->hashImageName('약사공론'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '약사신문', 'img_path' => $this->hashImageName('약사신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '약업신문', 'img_path' => $this->hashImageName('약업신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '어패럴뉴스', 'img_path' => $this->hashImageName('어패럴뉴스'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '에너지경제신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '여성농업인신문', 'img_path' => $this->hashImageName('여성농업인신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '연예정보신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '열린교육신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '영농자재신문', 'img_path' => $this->hashImageName('영농자재신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '옵틱위클리', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '운송신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '운수시보', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '원예산업신문', 'img_path' => $this->hashImageName('원예산업신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '원주신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '의사시보', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '의사신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '의학신문', 'img_path' => $this->hashImageName('의학신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '의학신보', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '의협신문', 'img_path' => $this->hashImageName('의협신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '이뉴스투데이', 'img_path' => $this->hashImageName('이뉴스투데이'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '인쇄문화시보', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '인쇄신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '일요신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '일요저널', 'img_path' => $this->hashImageName('일요저널'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '장업신문', 'img_path' => $this->hashImageName('장업신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '장학신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '전문건설신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '전업신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '정보통신신문', 'img_path' => $this->hashImageName('정보통신신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '제남신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '주간경찰', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '주간관광신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '주간기독공보', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '주간기독교', 'img_path' => $this->hashImageName('주간기독교'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '주간남도신보', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '주간만화', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '주간새마을신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '주간서해', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '주간섬유', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '주간식품저널', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '주간전기뉴스', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '주간전매', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '주간중앙', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '주간코스메틱', 'img_path' => $this->hashImageName('주간코스메틱'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '주간한국', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '중소기업뉴스', 'img_path' => $this->hashImageName('중소기업뉴스'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '축산경제신문', 'img_path' => $this->hashImageName('축산경제신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '축산신문', 'img_path' => $this->hashImageName('축산신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '치의신보', 'img_path' => $this->hashImageName('치의신보'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '코리아쉬핑가제트', 'img_path' => $this->hashImageName('코리아쉬핑가제트'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'KFF뉴스', 'img_path' => $this->hashImageName('KFF뉴스'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '타임즈코어', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '토요신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TV가이드', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '틴타임즈', 'img_path' => $this->hashImageName('틴타임즈'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '팜앤파켓', 'img_path' => $this->hashImageName('팜앤파켓'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국가스신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국건설신문', 'img_path' => $this->hashImageName('한국건설신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국경제신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국교육신문', 'img_path' => $this->hashImageName('한국교육신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국금융', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국금융신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국기독공보', 'img_path' => $this->hashImageName('한국기독공보'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국기독타임즈', 'img_path' => $this->hashImageName('한국기독타임즈'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국농업신문', 'img_path' => $this->hashImageName('한국농업신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국농촌경제신문', 'img_path' => $this->hashImageName('한국농촌경제신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국대학신문', 'img_path' => $this->hashImageName('한국대학신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국무역신문', 'img_path' => $this->hashImageName('한국무역신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국복음신보', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국섬유신문', 'img_path' => $this->hashImageName('한국섬유신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국성결신문', 'img_path' => $this->hashImageName('한국성결신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국세정신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국세정신보', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국수산신보', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국식약경제신문', 'img_path' => $this->hashImageName('한국식약경제신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국식품의약신문', 'img_path' => $this->hashImageName('한국식품의약신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국식품정보신문', 'img_path' => $this->hashImageName('한국식품정보신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국아파트신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국영농신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국의약신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국의약통신', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국임업신문', 'img_path' => $this->hashImageName('한국임업신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국전기신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국전문신문협회', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국주택신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국치안신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한국해운신문', 'img_path' => $this->hashImageName('한국해운신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한류앤뉴스통신', 'img_path' => $this->hashImageName('한류앤뉴스통신'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한북시보', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한우신문', 'img_path' => $this->hashImageName('한우신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '한의신문', 'img_path' => $this->hashImageName('한의신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '해피타임즈', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '현대경제일보', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '현대불교', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '헬스컨슈머', 'img_path' => $this->hashImageName('헬스컨슈머'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '화광신문', 'img_path' => $this->hashImageName('화광신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '화학저널', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '환경경영신문', 'img_path' => $this->hashImageName('환경경영신문'), 'created_at' => now(), 'updated_at' => now()],
            ['name' => '환경공업신문', 'img_path' => null, 'created_at' => now(), 'updated_at' => now()],
            ['name' => '환경타임즈', 'img_path' => $this->hashImageName('환경타임즈'), 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
    private function hashImageName($imageName)
    {
        // Normalize the image name
        if (class_exists('Normalizer')) {
            $normalized_name = \Normalizer::normalize($imageName, \Normalizer::FORM_C);
        } else {
            $normalized_name = $imageName;
        }

        // Encode the image name in UTF-8
        $encoded_name = utf8_encode($normalized_name);

        // Replace spaces with underscores (if required)
        $encoded_name = str_replace(' ', '_', $encoded_name);

        // Create a hash (SHA-256)
        $hash_hex = hash('sha256', $encoded_name);

        return 'partnership/'.$hash_hex.'.png';
    }
}
